openapi: 3.0.3
info:
  title: Library API
  version: 1.1.0
  description: STD22082
servers:
  - url: https://library.com
tags:
  - name: Books
  - name: Author
paths:
  /books:
    get:
      tags:
        - Books
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      parameters:
        - in: query
          name: bookName
          description: Filter return books by given name
          required: false
          schema:
            type: string
        # TODO3: add parameter to filter books by intervals of dates of the releaseDate
        - in: query
          name: releaseDate
          description: Filter books released on or after this date (YYYY-MM-DD)
          required: false
          schema:
            type: string
            format: date
        - in: query
          name: page
          description: default page
          required: false
          schema:
            type: integer
            default: 1
        - in: query
          name: pageSize
          description: default pageSize
          required: false
          schema:
            type: integer
            default: 50

      responses:
        200:
          description: The list of filtered books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
    put:
      tags:
        - Books
      summary: Create or update a list of books
      operationId: crupdateBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/CrupdateBook"
      responses:
        200:
          description: The list of created or updated books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
  # Attachement Author and Book
  /books/{bookId}/authors/{authorId}:
    put:
      tags:
        - Books
      summary: Associate an author with a book
      operationId: updateBookAuthor
      parameters:
        - in: path
          name: bookId
          required: true
          schema:
            type: string
        - in: path
          name: authorId
          required: true
          schema:
            type: string
      responses:
        200:
          description: The author of the book has been changed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
  /books/authors:
      put:
        tags:
        - Author
        summary: Update the author of books
        operationId: updateBooksAuthors
        requestBody:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UpdateBookAuthor"
        responses:
          200:
            description: Les auteurs des livres ont été modifiés
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/Book"
  /authors:
    # TODO2: complete GET (can be filtered by name) - PUT - DELETE
    get:
      tags:
        - Author
      summary: Get all authors
      description: Get a list of authors, optionally filtered by name
      operationId: getAuthors
      parameters:
        - in: query
          name: authorName
          description: Filter authors by name
          required: false
          schema:
            type: string
        - in: query
          name: page
          description: Filter authors by page
          required: false
          schema:
            type: integer
            default: 1
        - in: query
          name: pageSize
          description: Filter authors by pageSize
          required: false
          schema:
            type: integer
            default: 50
      responses:
        200:
          description: The list of authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/author"
    put:
      tags:
        - Author
      summary: Create or update an author
      operationId: createUpdateAuthor
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/author"
      responses:
        200:
          description: The created or updated author
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/author"
    delete:
      tags:
        - Books
      summary: Delete an author by ID
      description: Delete an author by their unique ID
      operationId: deleteAuthor
      parameters:
        - in: path
          name: authorId
          description: ID of the author to delete
          required: true
          schema:
            type: string
      responses:
        204:
          description: Author deleted successfully
components:
  schemas:
    Book:
      allOf:
        - $ref: "#/components/schemas/CrupdateBook"
      type: object
      properties:
        author:
          nullable: true
          #TODO1: set it as a component with properties : id, name, sex (M or F)
          $ref: "#/components/schemas/author"
    author:
      type: object
      properties:
        authorId:
          type: string
        authorNname:
          type: string
        sex:
          type: string
          enum:
            - M
            - F
    CrupdateBook:
      type: object
      properties:
        bookId:
          type: string
        bookName:
          type: string
        pageNumbers:
          type: integer
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
        releaseDate:
          type: string
          format: date
    UpdateBookAuthor:
     type: object
     properties:
      bookId:
        type: string
      authorId:
        type: string
